import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Sila',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { rel: 'icon', type: 'image/png', sizes: '32x32', url: '/favicon-32x32.png' },
      { rel: 'icon', type: 'image/png', sizes: '16x16', url: '/favicon-16x16.png' },
    ],
    apple: '/apple-touch-icon.png',
  },
  manifest: '/site.webmanifest',
  other: {
    'msapplication-TileColor': '#da532c',
    'mask-icon': '/safari-pinned-tab.svg',
    'mask-icon-color': '#5bbad5',
  },
}