import { ReactQueryProvider } from '@/app/providers'
import { Toaster } from '@/shared/ui'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '../src/app/styles/globals.css'
import '../src/shared/lib/i18n'
import { GoogleOAuthProvider } from '@react-oauth/google'
import Head from 'next/head'

const geistSans = localFont({
  src: '../src/app/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: '../src/app/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Sila',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />

        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <GoogleOAuthProvider
            clientId={process.env.GOOGLE_CLIENT_ID as string}
          >
            <main className="h-full">{children}</main>
            <Toaster position="top-right" richColors />
          </GoogleOAuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
