import Providers from '@/app/providers/Providers'
import { Toaster } from '@/shared/ui'
import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import localFont from 'next/font/local'
import '../src/app/styles/globals.css'

const geistSans = localFont({
  src: '../src/app/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: '../src/app/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Sila',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
  },
  icons: {
    icon: [
      { rel: 'icon', type: 'image/png', sizes: '32x32', url: '/favicon-32x32.png' },
      { rel: 'icon', type: 'image/png', sizes: '16x16', url: '/favicon-16x16.png' },
    ],
    apple: '/apple-touch-icon.png',
  },
  themeColor: '#ffffff',
  manifest: '/site.webmanifest',
  other: {
    'msapplication-TileColor': '#da532c',
    'mask-icon': '/safari-pinned-tab.svg',
    'mask-icon-color': '#5bbad5',
  },
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <NextIntlClientProvider messages={messages}>
            <main className="h-full">{children}</main>
          </NextIntlClientProvider>
          <Toaster position="top-right" richColors />
        </Providers>
      </body>
    </html>
  )
}
