// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/google/token": {
            "post": {
                "description": "Logs in a user using Google OAuth2 Access Token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Google OAuth2 Token Login",
                "parameters": [
                    {
                        "description": "Google OAuth2 Access Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GoogleTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Access and refresh tokens",
                        "schema": {
                            "$ref": "#/definitions/models.TokensResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload or access token is required",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get user info from Google or error creating/updating user",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "This endpoint logs in a user and returns tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login user",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tokens",
                        "schema": {
                            "$ref": "#/definitions/models.TokensResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/refresh-token": {
            "post": {
                "description": "Refreshes the access and refresh tokens using a valid refresh token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh JWT tokens",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "access_token\" \"refresh_token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error\" \"Invalid input or Refresh token required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error\" \"Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "This endpoint registers a new user with email, password, and username",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Register user",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tokens",
                        "schema": {
                            "$ref": "#/definitions/models.TokensResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Email already in use",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/validate-token": {
            "get": {
                "description": "This endpoint validates a user's JWT token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Validate user token",
                "responses": {
                    "200": {
                        "description": "Valid token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/exercises": {
            "get": {
                "description": "Get a list of all exercises with information on muscle groups in the requested language (English or Russian). Supports filtering by muscle_group_id and searching by name.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercises"
                ],
                "summary": "Get all exercises",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by muscle group ID",
                        "name": "muscle_group_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by exercise name (both in Russian and English)",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of exercises",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ExerciseResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve exercises",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new exercise with names in both English and Russian, and specify the muscle group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercises"
                ],
                "summary": "Create a new exercise",
                "parameters": [
                    {
                        "description": "Create new exercise",
                        "name": "exercise",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateExerciseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created exercise",
                        "schema": {
                            "$ref": "#/definitions/models.Exercise"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to create exercise",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/exercises/{id}": {
            "put": {
                "description": "Update an existing exercise with new names in both English and Russian, and update the muscle group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exercises"
                ],
                "summary": "Update an existing exercise",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Exercise ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update exercise",
                        "name": "exercise",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateExerciseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated exercise",
                        "schema": {
                            "$ref": "#/definitions/models.Exercise"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Exercise not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to update exercise",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/fitness-levels": {
            "get": {
                "description": "Получение списка всех уровней физической подготовки с названиями на английском и русском языках.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FitnessLevels"
                ],
                "summary": "Get all fitness levels",
                "responses": {
                    "200": {
                        "description": "List of fitness levels",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.FitnessLevel"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve fitness levels",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/muscle-groups": {
            "get": {
                "description": "Get a list of all muscle groups in the requested language (English or Russian).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MuscleGroups"
                ],
                "summary": "Get all muscle groups",
                "responses": {
                    "200": {
                        "description": "List of muscle groups",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.GetMuscleGroupsResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve muscle groups",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new muscle group with names in both English and Russian.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MuscleGroups"
                ],
                "summary": "Create a new muscle group",
                "parameters": [
                    {
                        "description": "Muscle group data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateMuscleGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created muscle group",
                        "schema": {
                            "$ref": "#/definitions/models.MuscleGroup"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to create muscle group",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/muscle-groups/{id}": {
            "put": {
                "description": "Обновление информации о группе мышц с учетом названий на двух языках.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MuscleGroups"
                ],
                "summary": "Update a muscle group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Muscle group ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated muscle group data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MuscleGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated muscle group",
                        "schema": {
                            "$ref": "#/definitions/models.MuscleGroup"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Muscle group not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to update muscle group",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the profile information of the authenticated user, including email, username, fitness level, avatar, and role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User Profile",
                "responses": {
                    "200": {
                        "description": "Returns the user profile data",
                        "schema": {
                            "$ref": "#/definitions/models.GetUserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "No token provided or invalid token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/workout/add-set/{id}": {
            "post": {
                "description": "This endpoint allows adding a set (reps and weight) to an ongoing workout session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workout"
                ],
                "summary": "Add a set to a workout session",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workout session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Set data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddSetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Set added successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid input or session ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Workout session not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to add set",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/workout/complete/{id}": {
            "put": {
                "description": "Marks a workout session as completed and allows adding a final note.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workout"
                ],
                "summary": "Complete a workout session",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workout session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Completion note",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CompleteWorkoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Workout session completed successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid input or session ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Workout session not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to complete workout session",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/workout/exercise/{exercise_id}": {
            "get": {
                "description": "Retrieve paginated workout sessions for a specific exercise for the authenticated user, with support for different languages.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workout"
                ],
                "summary": "Get workout sessions by exercise",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Exercise ID",
                        "name": "exercise_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of workout sessions",
                        "schema": {
                            "$ref": "#/definitions/models.PaginatedWorkoutResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid exercise ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve workout sessions",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/workout/exercise/{exercise_id}/history": {
            "get": {
                "description": "Retrieve paginated history of users who performed a specific exercise",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workout"
                ],
                "summary": "Get exercise history by users",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Exercise ID",
                        "name": "exercise_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of users' exercise history",
                        "schema": {
                            "$ref": "#/definitions/models.PaginatedExerciseHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid exercise ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve exercise history",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/workout/incomplete": {
            "get": {
                "description": "Retrieve all incomplete workout sessions for the authenticated user, with support for different languages.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workout"
                ],
                "summary": "Get incomplete workout sessions",
                "responses": {
                    "200": {
                        "description": "List of incomplete workouts",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.IncompleteWorkoutResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve incomplete workouts",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/workout/set/{id}": {
            "delete": {
                "description": "This endpoint allows deleting a set by its ID from a workout session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workout"
                ],
                "summary": "Delete a set from a workout session",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Set ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Set deleted successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid set ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "You do not have permission to delete this set",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Set not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to delete set",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/workout/start": {
            "post": {
                "description": "This endpoint starts a workout session for a specific exercise and optionally returns the last completed session if available.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workout"
                ],
                "summary": "Start a workout session",
                "parameters": [
                    {
                        "description": "Exercise ID",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.StartWorkoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "New workout session and last session (if any)",
                        "schema": {
                            "$ref": "#/definitions/models.StartWorkoutResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input or Exercise ID missing",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to start workout session",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/workout/{id}": {
            "get": {
                "description": "Retrieve details of a specific workout session including sets, exercise info, muscle group, and last session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workout"
                ],
                "summary": "Get details of a workout session",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workout session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Workout session details with last session",
                        "schema": {
                            "$ref": "#/definitions/models.WorkoutSessionResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid session ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Workout session not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "This endpoint allows deleting a workout session by its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workout"
                ],
                "summary": "Delete a workout session",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Workout session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Workout session deleted successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid session ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "You do not have permission to delete this workout session",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Workout session not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to delete workout session",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddSetRequest": {
            "type": "object",
            "required": [
                "reps",
                "weight"
            ],
            "properties": {
                "reps": {
                    "type": "integer",
                    "example": 10
                },
                "weight": {
                    "type": "number",
                    "example": 50.5
                }
            }
        },
        "models.CompleteWorkoutRequest": {
            "type": "object",
            "properties": {
                "note": {
                    "type": "string",
                    "example": "Great workout!"
                }
            }
        },
        "models.CreateExerciseRequest": {
            "type": "object",
            "required": [
                "muscle_group_id",
                "name_eng",
                "name_ru"
            ],
            "properties": {
                "description_eng": {
                    "type": "string",
                    "example": "A basic chest exercise."
                },
                "description_ru": {
                    "type": "string",
                    "example": "Базовое упражнение для груди."
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/benchpress.jpg"
                },
                "muscle_group_id": {
                    "type": "integer",
                    "example": 1
                },
                "name_eng": {
                    "type": "string",
                    "example": "Bench Press"
                },
                "name_ru": {
                    "type": "string",
                    "example": "Жим лежа"
                }
            }
        },
        "models.CreateMuscleGroupRequest": {
            "type": "object",
            "required": [
                "name_eng",
                "name_ru"
            ],
            "properties": {
                "image_url": {
                    "type": "string",
                    "example": "http://example.com/chest.jpg"
                },
                "name_eng": {
                    "type": "string",
                    "example": "Chest"
                },
                "name_ru": {
                    "type": "string",
                    "example": "Грудь"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.Exercise": {
            "type": "object",
            "required": [
                "name_eng",
                "name_ru"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description_eng": {
                    "type": "string"
                },
                "description_ru": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "muscle_group": {
                    "$ref": "#/definitions/models.MuscleGroup"
                },
                "name_eng": {
                    "type": "string"
                },
                "name_ru": {
                    "type": "string"
                }
            }
        },
        "models.ExerciseHistoryEntry": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "exercise": {
                    "$ref": "#/definitions/models.ExerciseResponse"
                },
                "is_completed": {
                    "type": "boolean"
                },
                "note": {
                    "type": "string"
                },
                "session_id": {
                    "type": "integer"
                },
                "sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Set"
                    }
                },
                "user": {
                    "$ref": "#/definitions/models.UserBasicInfo"
                }
            }
        },
        "models.ExerciseResponse": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "muscle_group",
                "name"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "muscle_group": {
                    "$ref": "#/definitions/models.GetMuscleGroupsResponse"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.FitnessLevel": {
            "type": "object",
            "required": [
                "name_eng",
                "name_ru"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name_eng": {
                    "type": "string"
                },
                "name_ru": {
                    "type": "string"
                }
            }
        },
        "models.GetMuscleGroupsResponse": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.GetUserProfileResponse": {
            "type": "object",
            "required": [
                "created_at",
                "email",
                "fitness_level",
                "role",
                "username"
            ],
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fitness_level": {
                    "type": "string"
                },
                "last_login": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.GoogleTokenRequest": {
            "type": "object",
            "required": [
                "access_token"
            ],
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "models.IncompleteWorkoutResponse": {
            "type": "object",
            "required": [
                "created_at",
                "exercise",
                "id",
                "is_completed",
                "sets"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "exercise": {
                    "$ref": "#/definitions/models.ExerciseResponse"
                },
                "id": {
                    "type": "integer"
                },
                "is_completed": {
                    "type": "boolean"
                },
                "note": {
                    "type": "string"
                },
                "sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Set"
                    }
                }
            }
        },
        "models.LastWorkoutSessionResponse": {
            "type": "object",
            "required": [
                "created_at",
                "exercise",
                "id",
                "is_completed",
                "sets"
            ],
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-10-01T10:00:00Z"
                },
                "exercise": {
                    "$ref": "#/definitions/models.ExerciseResponse"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_completed": {
                    "type": "boolean",
                    "example": true
                },
                "note": {
                    "type": "string",
                    "example": "Previous workout notes"
                },
                "sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Set"
                    }
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.MuscleGroup": {
            "type": "object",
            "required": [
                "name_eng",
                "name_ru"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string",
                    "example": "http://example.com/chest.jpg"
                },
                "name_eng": {
                    "type": "string",
                    "example": "Chest"
                },
                "name_ru": {
                    "type": "string",
                    "example": "Грудь"
                }
            }
        },
        "models.PaginatedExerciseHistoryResponse": {
            "type": "object",
            "required": [
                "items",
                "total"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ExerciseHistoryEntry"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.PaginatedWorkoutResponse": {
            "type": "object",
            "required": [
                "items",
                "total"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IncompleteWorkoutResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.Permission": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Provider": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                }
            }
        },
        "models.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "models.Role": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Permission"
                    }
                }
            }
        },
        "models.Set": {
            "type": "object",
            "required": [
                "created_at",
                "id",
                "reps",
                "weight",
                "workout_session_id"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reps": {
                    "type": "integer"
                },
                "weight": {
                    "type": "number"
                },
                "workout_session_id": {
                    "type": "integer"
                }
            }
        },
        "models.StartWorkoutRequest": {
            "type": "object",
            "required": [
                "exercise_id"
            ],
            "properties": {
                "exercise_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.StartWorkoutResponse": {
            "type": "object",
            "required": [
                "created_at",
                "is_completed",
                "session_id"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "is_completed": {
                    "type": "boolean"
                },
                "last_session": {
                    "$ref": "#/definitions/models.WorkoutSessionResponse"
                },
                "session_id": {
                    "type": "integer"
                }
            }
        },
        "models.TokensResponse": {
            "type": "object",
            "required": [
                "access_token",
                "refresh_token"
            ],
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "models.UpdateExerciseRequest": {
            "type": "object",
            "required": [
                "muscle_group_id",
                "name_eng",
                "name_ru"
            ],
            "properties": {
                "description_eng": {
                    "type": "string",
                    "example": "A basic chest exercise."
                },
                "description_ru": {
                    "type": "string",
                    "example": "Базовое упражнение для груди."
                },
                "image_url": {
                    "type": "string",
                    "example": "https://example.com/benchpress.jpg"
                },
                "muscle_group_id": {
                    "type": "integer",
                    "example": 1
                },
                "name_eng": {
                    "type": "string",
                    "example": "Bench Press"
                },
                "name_ru": {
                    "type": "string",
                    "example": "Жим лежа"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fitness_level": {
                    "$ref": "#/definitions/models.FitnessLevel"
                },
                "fitness_level_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "last_login": {
                    "type": "string"
                },
                "provider": {
                    "$ref": "#/definitions/models.Provider"
                },
                "provider_id": {
                    "type": "integer"
                },
                "provider_user_id": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/models.Role"
                },
                "role_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserBasicInfo": {
            "type": "object",
            "required": [
                "email",
                "id",
                "username"
            ],
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.WorkoutSessionResponse": {
            "type": "object",
            "required": [
                "created_at",
                "exercise",
                "id",
                "is_completed",
                "sets",
                "user"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "exercise": {
                    "$ref": "#/definitions/models.ExerciseResponse"
                },
                "id": {
                    "type": "integer"
                },
                "is_completed": {
                    "type": "boolean"
                },
                "last_session": {
                    "$ref": "#/definitions/models.LastWorkoutSessionResponse"
                },
                "note": {
                    "type": "string"
                },
                "sets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Set"
                    }
                },
                "user": {
                    "$ref": "#/definitions/models.UserBasicInfo"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "sila-danila.ru",
	BasePath:         "/api",
	Schemes:          []string{"http,", "https"},
	Title:            "Sila API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
