name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "URL для тестирования"
        required: true
        default: "https://sila-danila.ru"
        type: string

jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: e2e-tests/package.json

      - name: Cache node_modules
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: e2e-tests/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('e2e-tests/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('e2e-tests/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: |
          cd e2e-tests
          npm install

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          cd e2e-tests
          npx playwright install --with-deps chromium webkit

      - name: Create .env file with login credentials
        run: |
          cd e2e-tests
          cat > .env << EOF
          TEST_USERNAME=${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD=${{ secrets.TEST_PASSWORD }}
          BASE_URL=${{ inputs.base_url }}
          EOF

      - name: Run E2E tests
        run: |
          cd e2e-tests
          npm test

      - name: Archive test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 30
