name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "URL для тестирования"
        required: true
        default: "https://sila-danila.ru"
        type: string

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd e2e-tests
          npm install
          npx playwright install --with-deps chromium webkit

      - name: Create .env file with login credentials
        run: |
          cd e2e-tests
          cat > .env << EOF
          TEST_USERNAME=${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD=${{ secrets.TEST_PASSWORD }}
          BASE_URL=${{ github.event.inputs.base_url }}
          EOF

      - name: Run E2E tests
        run: |
          cd e2e-tests
          npm test

      - name: Archive test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 30
